# Mejorar viviendas

En este notebook se pretende hacer lo siguiente:


1. Recoger las descripciones de las viviendas de los anuncios.
2. Pasar un MLL para extraer más información de las descripciones.
3. Enriquecer el dataset actual.

## Dependencias

In [1]:
# Librerías generales
import pandas as pd
import numpy as np

from urllib.request import urlopen
from bs4 import BeautifulSoup

import re

In [2]:
# Cargamos Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ruta = '/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/pisos_descripcion.csv'
ruta = '/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/pisos_con_descripción_filtrado.csv'

pisos = pd.read_csv(ruta, sep=';')

In [ ]:
pisos.head()

,tipo,precio,localidad,latitud,longitud,superficie_construida,habitaciones,banyos,antiguedad,conservacion,...,orientacion,garaje,piscina,aire_acondicionado,trastero,ascensor,planta,fecha,detalle_url,Descripcion
0,Piso,139000,Ibi,38.624174,-0.574839,120.0,4.0,1.0,Entre 30 y 50 años,En buen estado,...,Este,Desconocido,Sin piscina,False,True,True,4ª,2026-02-24,https://www.pisos.com/comprar/piso-ibi_centro_...,En el municipio de ibi se encuentra este ampli...
1,Piso,200000,La Vila Joiosa Villajoyosa,38.502493,-0.241090,85.0,3.0,2.0,Entre 10 y 20 años,En buen estado,...,Desconocido,Desconocido,Sin piscina,True,True,True,0ª,2026-02-24,https://www.pisos.com/comprar/piso-montiboli_p...,"Piso en planta baja, superficie 85 m². Cuenta ..."
2,Ático,490000,Alicante Alacant,38.372956,-0.418654,125.0,3.0,2.0,Entre 10 y 20 años,A estrenar,...,Todos,Privado,Exterior,True,False,True,10ª,2026-02-02,https://www.pisos.com/comprar/atico-playas_pla...,"Superf. 125 m², 3 habitaciones ( 1 suite, 2 ..."
3,Piso,193700,Finestrat,38.528848,-0.165879,70.0,2.0,1.0,Entre 30 y 50 años,En buen estado,...,Desconocido,Privado,Exterior,False,False,True,1ª,2026-02-24,https://www.pisos.com/comprar/piso-finestrat_c...,En La Cala de Finestrat se encuentra este enca...
4,Chalet,298000,Sax,38.525305,-0.815885,531.0,5.0,2.0,Entre 10 y 20 años,En buen estado,...,Desconocido,Privado,Sin piscina,False,False,False,0ª,2025-12-11,https://www.pisos.com/comprar/chalet_rustico-s...,"Espectacular chalet independiente en Sax, con ..."

## Recolección de las descripciones

Primero vamos a añadir las descripciones de los anuncios a su respectiva vivienda:

In [ ]:
df = pisos.copy()

# Creamos la columna con Desconocida primero:
# df['Descripcion'] = 'Desconocida' lo comentamos porque sino sobreescribe lo que llevamos cuando volvemos a ejecutar

df.head()

,tipo,precio,localidad,latitud,longitud,superficie_construida,habitaciones,banyos,antiguedad,conservacion,...,orientacion,garaje,piscina,aire_acondicionado,trastero,ascensor,planta,fecha,detalle_url,Descripcion
0,Ático,70000,Alcoi Alcoy,38.700241,-0.481300,90.0,2.0,1.0,Entre 5 y 10 años,En buen estado,...,Desconocido,Desconocido,Sin piscina,False,True,False,5ª,2025-12-23,https://www.pisos.com/comprar/atico-alcoi_alco...,Desconocida_Revisada
1,Piso,139000,Ibi,38.624174,-0.574839,120.0,4.0,1.0,Entre 30 y 50 años,En buen estado,...,Este,Desconocido,Sin piscina,False,True,True,4ª,2026-02-24,https://www.pisos.com/comprar/piso-ibi_centro_...,En el municipio de ibi se encuentra este ampli...
2,Ático,950000,Alicante Alacant,38.380730,-0.410119,100.0,3.0,2.0,Desconocida,A reformar,...,Sur-Este,Privado,Comunitaria,False,False,True,10ª,2026-02-02,https://www.pisos.com/comprar/atico-playas_pla...,Desconocida_Revisada
3,Piso,200000,La Vila Joiosa Villajoyosa,38.502493,-0.241090,85.0,3.0,2.0,Entre 10 y 20 años,En buen estado,...,Desconocido,Desconocido,Sin piscina,True,True,True,0ª,2026-02-24,https://www.pisos.com/comprar/piso-montiboli_p...,"Piso en planta baja, superficie 85 m². Cuenta ..."
4,Piso,115000,Alcoi Alcoy,38.691936,-0.488745,90.0,4.0,2.0,Desconocida,En buen estado,...,Desconocido,Privado,Sin piscina,False,True,True,0ª,NaN,https://www.pisos.com/comprar/piso-alcoi_alcoy...,Desconocida_Revisada

In [ ]:
df['detalle_url'].iloc[1]

'https://www.pisos.com/comprar/piso-ibi_centro_urbano-58089976_443300/'

### Prueba

Vamos a hacer una prueba. Este url: https://www.pisos.com/comprar/piso-ibi_centro_urbano-58089976_443300/. Nos debería de devolver esta descrpición:

En el municipio de ibi se encuentra este amplio piso en venta, situado en la planta 4ª y con una superficie total de 120 m². El piso cuenta con 2 habitaciones individuales, 2 habitaciones dobles, 1 baño, balcón amplio, calefacción de calor azul, cocina reformada y muy amplia, comedor espacioso y luminoso con balcón, armarios empotrados, ascensor, suelo de terrazo y trastero en la misma vivienda más otro amplio en la terraza. El estado de conservación es bueno y está amueblado. La orientación es este, lo que garantiza una vivienda soleada. Además, el edificio dispone de terraza comunitaria y el nivel energético es clase e, con emisiones de 39 y consumo de 195. ¡No dejes pasar esta oportunidad de adquirir este acogedor piso en ibi! En pvp no incluidos los gastos de escrituración, registro, gestoría, impuestos, notaria y gestión de la inmobiliaria

In [ ]:
url = 'https://www.pisos.com/comprar/piso-ibi_centro_urbano-58089976_443300/'

html = urlopen(url, timeout=30)
soup = BeautifulSoup(html, "html.parser")

# Buscamos el div por su clase específica
div_descripcion = soup.find("div", class_="description__content")

if div_descripcion:
    # Extraemos el texto y eliminamos los espacios y saltos de línea sobrantes
    texto_descripcion = div_descripcion.text.strip()
    print(texto_descripcion)
else:
    print("No se encontró la descripción.")

En el municipio de ibi se encuentra este amplio piso en venta, situado en la planta 4ª y con una superficie total de 120 m². El piso cuenta con 2 habitaciones individuales, 2 habitaciones dobles, 1 baño, balcón amplio, calefacción de calor azul, cocina reformada y muy amplia, comedor espacioso y luminoso con balcón, armarios empotrados, ascensor, suelo de terrazo y trastero en la misma vivienda más otro amplio en la terraza. El estado de conservación es bueno y está amueblado. La orientación es este, lo que garantiza una vivienda soleada. Además, el edificio dispone de terraza comunitaria y el nivel energético es clase e, con emisiones de 39 y consumo de 195. ¡No dejes pasar esta oportunidad de adquirir este acogedor piso en ibi! En pvp no incluidos los gastos de escrituración, registro, gestoría, impuestos, notaria y gestión de la inmobiliaria

### Proceso

Ahora generalizamos el proceso para todas las filas del data frame:

In [ ]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

def obtener_descripcion(url):
    """
    Conecta a la URL y extrae el texto del div 'description__content'.
    Si hay un error o no lo encuentra, devuelve None.
    """
    try:
        html = urlopen(url, timeout=30)
        soup = BeautifulSoup(html, "html.parser")

        div_descripcion = soup.find("div", class_="description__content")

        if div_descripcion:
            return div_descripcion.text.strip()
        return None

    except Exception as e:
        print(f"Error al acceder a {url}: {e}")
        return None

In [ ]:
def actualizar_descripciones(df):
    """
    Recorre el DataFrame buscando descripciones 'Desconocida',
    las extrae de la web y guarda el progreso en el archivo CSV.
    """
    actualizadas = 0  # contador de actualizaciones

    for idx in df.index:
        if df.loc[idx, "Descripcion"] == "Desconocida":

            url = df.loc[idx, "detalle_url"]
            descripcion = obtener_descripcion(url)

            if descripcion:
                df.loc[idx, "Descripcion"] = descripcion
                actualizadas += 1

                # Guardamos el progreso tras cada acierto
                df.to_csv(ruta,
                          index=False,
                          sep=";",
                          encoding="utf-8")

                print(f"Fila actualizada: {idx} | CSV sobrescrito con éxito | Total actualizadas: {actualizadas}")

            else:
                # Si falla la descarga o no existe el div, marcamos para no reintentar infinitamente
                df.loc[idx, "Descripcion"] = "Desconocida_Revisada"

    print(f"\nTotal descripciones actualizadas correctamente: {actualizadas}")
    return df

In [ ]:
# actualizar_descripciones(df)

Fila actualizada: 35269 | CSV sobrescrito con éxito | Total actualizadas: 1
Fila actualizada: 35272 | CSV sobrescrito con éxito | Total actualizadas: 2
Fila actualizada: 35282 | CSV sobrescrito con éxito | Total actualizadas: 3
Fila actualizada: 35286 | CSV sobrescrito con éxito | Total actualizadas: 4
Fila actualizada: 35292 | CSV sobrescrito con éxito | Total actualizadas: 5
Fila actualizada: 35293 | CSV sobrescrito con éxito | Total actualizadas: 6
Fila actualizada: 35294 | CSV sobrescrito con éxito | Total actualizadas: 7
Fila actualizada: 35296 | CSV sobrescrito con éxito | Total actualizadas: 8
Fila actualizada: 35298 | CSV sobrescrito con éxito | Total actualizadas: 9
Fila actualizada: 35306 | CSV sobrescrito con éxito | Total actualizadas: 10
Fila actualizada: 35307 | CSV sobrescrito con éxito | Total actualizadas: 11
Fila actualizada: 35310 | CSV sobrescrito con éxito | Total actualizadas: 12
Fila actualizada: 35311 | CSV sobrescrito con éxito | Total actualizadas: 13
Fila actualizada: 35317 | CSV sobrescrito con éxito | Total actualizadas: 14
Fila actualizada: 35330 | CSV sobrescrito con éxito | Total actualizadas: 15
Fila actualizada: 35332 | CSV sobrescrito con éxito | Total actualizadas: 16
Fila actualizada: 35333 | CSV sobrescrito con éxito | Total actualizadas: 17
Fila actualizada: 35340 | CSV sobrescrito con éxito | Total actualizadas: 18
Fila actualizada: 35344 | CSV sobrescrito con éxito | Total actualizadas: 19
Fila actualizada: 35351 | CSV sobrescrito con éxito | Total actualizadas: 20
Fila actualizada: 35352 | CSV sobrescrito con éxito | Total actualizadas: 21
Fila actualizada: 35355 | CSV sobrescrito con éxito | Total actualizadas: 22
Fila actualizada: 35358 | CSV sobrescrito con éxito | Total actualizadas: 23
Fila actualizada: 35359 | CSV sobrescrito con éxito | Total actualizadas: 24
Fila actualizada: 35362 | CSV sobrescrito con éxito | Total actualizadas: 25
Fila actualizada: 35368 | CSV sobrescrito con éxito | Total actualizadas: 26
Fila actualizada: 35369 | CSV sobrescrito con éxito | Total actualizadas: 27
Fila actualizada: 35373 | CSV sobrescrito con éxito | Total actualizadas: 28
Fila actualizada: 35378 | CSV sobrescrito con éxito | Total actualizadas: 29
Fila actualizada: 35383 | CSV sobrescrito con éxito | Total actualizadas: 30
Fila actualizada: 35384 | CSV sobrescrito con éxito | Total actualizadas: 31
Fila actualizada: 35402 | CSV sobrescrito con éxito | Total actualizadas: 32
Fila actualizada: 35404 | CSV sobrescrito con éxito | Total actualizadas: 33
Fila actualizada: 35405 | CSV sobrescrito con éxito | Total actualizadas: 34
Fila actualizada: 35407 | CSV sobrescrito con éxito | Total actualizadas: 35
Fila actualizada: 35410 | CSV sobrescrito con éxito | Total actualizadas: 36
Fila actualizada: 35431 | CSV sobrescrito con éxito | Total actualizadas: 37
Fila actualizada: 35437 | CSV sobrescrito con éxito | Total actualizadas: 38
Fila actualizada: 35439 | CSV sobrescrito con éxito | Total actualizadas: 39
Fila actualizada: 35440 | CSV sobrescrito con éxito | Total actualizadas: 40
Fila actualizada: 35454 | CSV sobrescrito con éxito | Total actualizadas: 41
Fila actualizada: 35455 | CSV sobrescrito con éxito | Total actualizadas: 42
Fila actualizada: 35464 | CSV sobrescrito con éxito | Total actualizadas: 43
Fila actualizada: 35468 | CSV sobrescrito con éxito | Total actualizadas: 44
Fila actualizada: 35471 | CSV sobrescrito con éxito | Total actualizadas: 45
Fila actualizada: 35473 | CSV sobrescrito con éxito | Total actualizadas: 46
Fila actualizada: 35478 | CSV sobrescrito con éxito | Total actualizadas: 47
Fila actualizada: 35483 | CSV sobrescrito con éxito | Total actualizadas: 48
Fila actualizada: 35484 | CSV sobrescrito con éxito | Total actualizadas: 49
Fila actualizada: 35488 | CSV sobrescrito con éxito | Total actualizadas: 50
Fila actualizada: 35493 | CSV sobrescrito con éxito | Total actualizadas: 51
Fila actualizada: 35494 | CSV sobrescrito con éxito | Total actualizadas: 52
Fila actualizada: 35501 | CSV sobrescrito con éxito | Total actualizadas: 53
Fila actualizada: 35504 | CSV sobrescrito con éxito | Total actualizadas: 54
Fila actualizada: 35505 | CSV sobrescrito con éxito | Total actualizadas: 55
Fila actualizada: 35507 | CSV sobrescrito con éxito | Total actualizadas: 56
Fila actualizada: 35514 | CSV sobrescrito con éxito | Total actualizadas: 57
Fila actualizada: 35524 | CSV sobrescrito con éxito | Total actualizadas: 58
Fila actualizada: 35531 | CSV sobrescrito con éxito | Total actualizadas: 59
Fila actualizada: 35532 | CSV sobrescrito con éxito | Total actualizadas: 60
Fila actualizada: 35552 | CSV sobrescrito con éxito | Total actualizadas: 61
Fila actualizada: 35553 | CSV sobrescrito con éxito | Total actualizadas: 62
Fila actualizada: 35559 | CSV sobrescrito con éxito | Total actualizadas: 63
Fila actualizada: 35562 | CSV sobrescrito con éxito | Total actualizadas: 64
Fila actualizada: 35563 | CSV sobrescrito con éxito | Total actualizadas: 65
Fila actualizada: 35572 | CSV sobrescrito con éxito | Total actualizadas: 66
Fila actualizada: 35578 | CSV sobrescrito con éxito | Total actualizadas: 67
Fila actualizada: 35580 | CSV sobrescrito con éxito | Total actualizadas: 68
Fila actualizada: 35582 | CSV sobrescrito con éxito | Total actualizadas: 69
Fila actualizada: 35586 | CSV sobrescrito con éxito | Total actualizadas: 70
Fila actualizada: 35587 | CSV sobrescrito con éxito | Total actualizadas: 71
Fila actualizada: 35590 | CSV sobrescrito con éxito | Total actualizadas: 72
Fila actualizada: 35594 | CSV sobrescrito con éxito | Total actualizadas: 73
Fila actualizada: 35600 | CSV sobrescrito con éxito | Total actualizadas: 74
Fila actualizada: 35608 | CSV sobrescrito con éxito | Total actualizadas: 75
Fila actualizada: 35609 | CSV sobrescrito con éxito | Total actualizadas: 76
Fila actualizada: 35618 | CSV sobrescrito con éxito | Total actualizadas: 77
Fila actualizada: 35619 | CSV sobrescrito con éxito | Total actualizadas: 78
Fila actualizada: 35620 | CSV sobrescrito con éxito | Total actualizadas: 79
Fila actualizada: 35626 | CSV sobrescrito con éxito | Total actualizadas: 80
Fila actualizada: 35628 | CSV sobrescrito con éxito | Total actualizadas: 81
Fila actualizada: 35629 | CSV sobrescrito con éxito | Total actualizadas: 82
Fila actualizada: 35630 | CSV sobrescrito con éxito | Total actualizadas: 83
Fila actualizada: 35635 | CSV sobrescrito con éxito | Total actualizadas: 84
Fila actualizada: 35637 | CSV sobrescrito con éxito | Total actualizadas: 85
Fila actualizada: 35638 | CSV sobrescrito con éxito | Total actualizadas: 86
Fila actualizada: 35639 | CSV sobrescrito con éxito | Total actualizadas: 87
Fila actualizada: 35641 | CSV sobrescrito con éxito | Total actualizadas: 88
Fila actualizada: 35644 | CSV sobrescrito con éxito | Total actualizadas: 89
Fila actualizada: 35645 | CSV sobrescrito con éxito | Total actualizadas: 90
Fila actualizada: 35657 | CSV sobrescrito con éxito | Total actualizadas: 91
Fila actualizada: 35661 | CSV sobrescrito con éxito | Total actualizadas: 92
Fila actualizada: 35672 | CSV sobrescrito con éxito | Total actualizadas: 93
Fila actualizada: 35684 | CSV sobrescrito con éxito | Total actualizadas: 94
Fila actualizada: 35691 | CSV sobrescrito con éxito | Total actualizadas: 95
Fila actualizada: 35692 | CSV sobrescrito con éxito | Total actualizadas: 96
Fila actualizada: 35694 | CSV sobrescrito con éxito | Total actualizadas: 97
Fila actualizada: 35700 | CSV sobrescrito con éxito | Total actualizadas: 98
Fila actualizada: 35702 | CSV sobrescrito con éxito | Total actualizadas: 99
Fila actualizada: 35708 | CSV sobrescrito con éxito | Total actualizadas: 100
Fila actualizada: 35709 | CSV sobrescrito con éxito | Total actualizadas: 101
Fila actualizada: 35710 | CSV sobrescrito con éxito | Total actualizadas: 102
Fila actualizada: 35714 | CSV sobrescrito con éxito | Total actualizadas: 103
Fila actualizada: 35716 | CSV sobrescrito con éxito | Total actualizadas: 104
Fila actualizada: 35723 | CSV sobrescrito con éxito | Total actualizadas: 105
Fila actualizada: 35729 | CSV sobrescrito con éxito | Total actualizadas: 106
Fila actualizada: 35731 | CSV sobrescrito con éxito | Total actualizadas: 107
Fila actualizada: 35738 | CSV sobrescrito con éxito | Total actualizadas: 108
Fila actualizada: 35749 | CSV sobrescrito con éxito | Total actualizadas: 109
Fila actualizada: 35750 | CSV sobrescrito con éxito | Total actualizadas: 110
Fila actualizada: 35752 | CSV sobrescrito con éxito | Total actualizadas: 111
Fila actualizada: 35765 | CSV sobrescrito con éxito | Total actualizadas: 112
Fila actualizada: 35770 | CSV sobrescrito con éxito | Total actualizadas: 113
Fila actualizada: 35772 | CSV sobrescrito con éxito | Total actualizadas: 114
Fila actualizada: 35773 | CSV sobrescrito con éxito | Total actualizadas: 115
Fila actualizada: 35774 | CSV sobrescrito con éxito | Total actualizadas: 116
Fila actualizada: 35775 | CSV sobrescrito con éxito | Total actualizadas: 117
Fila actualizada: 35779 | CSV sobrescrito con éxito | Total actualizadas: 118
Fila actualizada: 35785 | CSV sobrescrito con éxito | Total actualizadas: 119
Fila actualizada: 35787 | CSV sobrescrito con éxito | Total actualizadas: 120
Fila actualizada: 35788 | CSV sobrescrito con éxito | Total actualizadas: 121
Fila actualizada: 35791 | CSV sobrescrito con éxito | Total actualizadas: 122
Fila actualizada: 35794 | CSV sobrescrito con éxito | Total actualizadas: 123
Fila actualizada: 35800 | CSV sobrescrito con éxito | Total actualizadas: 124
Fila actualizada: 35801 | CSV sobrescrito con éxito | Total actualizadas: 125
Fila actualizada: 35803 | CSV sobrescrito con éxito | Total actualizadas: 126
Fila actualizada: 35806 | CSV sobrescrito con éxito | Total actualizadas: 127
Fila actualizada: 35807 | CSV sobrescrito con éxito | Total actualizadas: 128
Fila actualizada: 35808 | CSV sobrescrito con éxito | Total actualizadas: 129
Fila actualizada: 35809 | CSV sobrescrito con éxito | Total actualizadas: 130
Fila actualizada: 35810 | CSV sobrescrito con éxito | Total actualizadas: 131
Fila actualizada: 35818 | CSV sobrescrito con éxito | Total actualizadas: 132
Fila actualizada: 35820 | CSV sobrescrito con éxito | Total actualizadas: 133
Fila actualizada: 35822 | CSV sobrescrito con éxito | Total actualizadas: 134
Fila actualizada: 35825 | CSV sobrescrito con éxito | Total actualizadas: 135
Fila actualizada: 35830 | CSV sobrescrito con éxito | Total actualizadas: 136
Fila actualizada: 35831 | CSV sobrescrito con éxito | Total actualizadas: 137
Fila actualizada: 35832 | CSV sobrescrito con éxito | Total actualizadas: 138
Fila actualizada: 35833 | CSV sobrescrito con éxito | Total actualizadas: 139
Fila actualizada: 35838 | CSV sobrescrito con éxito | Total actualizadas: 140
Fila actualizada: 35839 | CSV sobrescrito con éxito | Total actualizadas: 141
Fila actualizada: 35844 | CSV sobrescrito con éxito | Total actualizadas: 142
Fila actualizada: 35855 | CSV sobrescrito con éxito | Total actualizadas: 143
Fila actualizada: 35858 | CSV sobrescrito con éxito | Total actualizadas: 144
Fila actualizada: 35860 | CSV sobrescrito con éxito | Total actualizadas: 145
Fila actualizada: 35861 | CSV sobrescrito con éxito | Total actualizadas: 146
Fila actualizada: 35865 | CSV sobrescrito con éxito | Total actualizadas: 147
Fila actualizada: 35866 | CSV sobrescrito con éxito | Total actualizadas: 148
Fila actualizada: 35870 | CSV sobrescrito con éxito | Total actualizadas: 149
Fila actualizada: 35878 | CSV sobrescrito con éxito | Total actualizadas: 150
Fila actualizada: 35882 | CSV sobrescrito con éxito | Total actualizadas: 151
Fila actualizada: 35883 | CSV sobrescrito con éxito | Total actualizadas: 152
Fila actualizada: 35884 | CSV sobrescrito con éxito | Total actualizadas: 153
Fila actualizada: 35887 | CSV sobrescrito con éxito | Total actualizadas: 154
Fila actualizada: 35895 | CSV sobrescrito con éxito | Total actualizadas: 155
Fila actualizada: 35900 | CSV sobrescrito con éxito | Total actualizadas: 156
Fila actualizada: 35903 | CSV sobrescrito con éxito | Total actualizadas: 157
Fila actualizada: 35908 | CSV sobrescrito con éxito | Total actualizadas: 158
Fila actualizada: 35911 | CSV sobrescrito con éxito | Total actualizadas: 159
Fila actualizada: 35913 | CSV sobrescrito con éxito | Total actualizadas: 160
Fila actualizada: 35917 | CSV sobrescrito con éxito | Total actualizadas: 161
Fila actualizada: 35921 | CSV sobrescrito con éxito | Total actualizadas: 162
Fila actualizada: 35924 | CSV sobrescrito con éxito | Total actualizadas: 163
Fila actualizada: 35926 | CSV sobrescrito con éxito | Total actualizadas: 164
Fila actualizada: 35929 | CSV sobrescrito con éxito | Total actualizadas: 165
Fila actualizada: 35938 | CSV sobrescrito con éxito | Total actualizadas: 166
Fila actualizada: 35939 | CSV sobrescrito con éxito | Total actualizadas: 167
Fila actualizada: 35940 | CSV sobrescrito con éxito | Total actualizadas: 168
Fila actualizada: 35941 | CSV sobrescrito con éxito | Total actualizadas: 169
Fila actualizada: 35944 | CSV sobrescrito con éxito | Total actualizadas: 170
Fila actualizada: 35946 | CSV sobrescrito con éxito | Total actualizadas: 171
Fila actualizada: 35955 | CSV sobrescrito con éxito | Total actualizadas: 172
Fila actualizada: 35956 | CSV sobrescrito con éxito | Total actualizadas: 173
Fila actualizada: 35957 | CSV sobrescrito con éxito | Total actualizadas: 174
Fila actualizada: 35969 | CSV sobrescrito con éxito | Total actualizadas: 175
Fila actualizada: 35974 | CSV sobrescrito con éxito | Total actualizadas: 176
Fila actualizada: 35975 | CSV sobrescrito con éxito | Total actualizadas: 177
Fila actualizada: 35982 | CSV sobrescrito con éxito | Total actualizadas: 178
Fila actualizada: 35983 | CSV sobrescrito con éxito | Total actualizadas: 179
Fila actualizada: 35987 | CSV sobrescrito con éxito | Total actualizadas: 180
Fila actualizada: 35990 | CSV sobrescrito con éxito | Total actualizadas: 181
Fila actualizada: 35993 | CSV sobrescrito con éxito | Total actualizadas: 182
Fila actualizada: 35994 | CSV sobrescrito con éxito | Total actualizadas: 183
Fila actualizada: 36000 | CSV sobrescrito con éxito | Total actualizadas: 184
Fila actualizada: 36006 | CSV sobrescrito con éxito | Total actualizadas: 185
Fila actualizada: 36009 | CSV sobrescrito con éxito | Total actualizadas: 186
Fila actualizada: 36013 | CSV sobrescrito con éxito | Total actualizadas: 187
Fila actualizada: 36014 | CSV sobrescrito con éxito | Total actualizadas: 188
Fila actualizada: 36019 | CSV sobrescrito con éxito | Total actualizadas: 189
Fila actualizada: 36021 | CSV sobrescrito con éxito | Total actualizadas: 190
Fila actualizada: 36022 | CSV sobrescrito con éxito | Total actualizadas: 191
Fila actualizada: 36023 | CSV sobrescrito con éxito | Total actualizadas: 192
Fila actualizada: 36024 | CSV sobrescrito con éxito | Total actualizadas: 193
Fila actualizada: 36026 | CSV sobrescrito con éxito | Total actualizadas: 194
Fila actualizada: 36038 | CSV sobrescrito con éxito | Total actualizadas: 195
Fila actualizada: 36039 | CSV sobrescrito con éxito | Total actualizadas: 196
Fila actualizada: 36044 | CSV sobrescrito con éxito | Total actualizadas: 197
Fila actualizada: 36045 | CSV sobrescrito con éxito | Total actualizadas: 198
Fila actualizada: 36046 | CSV sobrescrito con éxito | Total actualizadas: 199
Fila actualizada: 36047 | CSV sobrescrito con éxito | Total actualizadas: 200
Fila actualizada: 36058 | CSV sobrescrito con éxito | Total actualizadas: 201
Fila actualizada: 36062 | CSV sobrescrito con éxito | Total actualizadas: 202
Fila actualizada: 36063 | CSV sobrescrito con éxito | Total actualizadas: 203
Fila actualizada: 36064 | CSV sobrescrito con éxito | Total actualizadas: 204
Fila actualizada: 36068 | CSV sobrescrito con éxito | Total actualizadas: 205
Fila actualizada: 36082 | CSV sobrescrito con éxito | Total actualizadas: 206
Fila actualizada: 36084 | CSV sobrescrito con éxito | Total actualizadas: 207
Fila actualizada: 36087 | CSV sobrescrito con éxito | Total actualizadas: 208
Fila actualizada: 36088 | CSV sobrescrito con éxito | Total actualizadas: 209
Fila actualizada: 36089 | CSV sobrescrito con éxito | Total actualizadas: 210
Fila actualizada: 36098 | CSV sobrescrito con éxito | Total actualizadas: 211
Fila actualizada: 36101 | CSV sobrescrito con éxito | Total actualizadas: 212
Fila actualizada: 36104 | CSV sobrescrito con éxito | Total actualizadas: 213
Fila actualizada: 36105 | CSV sobrescrito con éxito | Total actualizadas: 214
Fila actualizada: 36106 | CSV sobrescrito con éxito | Total actualizadas: 215
Fila actualizada: 36110 | CSV sobrescrito con éxito | Total actualizadas: 216
Fila actualizada: 36112 | CSV sobrescrito con éxito | Total actualizadas: 217
Fila actualizada: 36113 | CSV sobrescrito con éxito | Total actualizadas: 218
Fila actualizada: 36114 | CSV sobrescrito con éxito | Total actualizadas: 219
Fila actualizada: 36121 | CSV sobrescrito con éxito | Total actualizadas: 220
Fila actualizada: 36129 | CSV sobrescrito con éxito | Total actualizadas: 221
Fila actualizada: 36130 | CSV sobrescrito con éxito | Total actualizadas: 222
Fila actualizada: 36131 | CSV sobrescrito con éxito | Total actualizadas: 223
Fila actualizada: 36135 | CSV sobrescrito con éxito | Total actualizadas: 224
Fila actualizada: 36142 | CSV sobrescrito con éxito | Total actualizadas: 225
Fila actualizada: 36154 | CSV sobrescrito con éxito | Total actualizadas: 226
Fila actualizada: 36162 | CSV sobrescrito con éxito | Total actualizadas: 227
Fila actualizada: 36166 | CSV sobrescrito con éxito | Total actualizadas: 228
Fila actualizada: 36170 | CSV sobrescrito con éxito | Total actualizadas: 229
Fila actualizada: 36173 | CSV sobrescrito con éxito | Total actualizadas: 230
Fila actualizada: 36175 | CSV sobrescrito con éxito | Total actualizadas: 231
Fila actualizada: 36176 | CSV sobrescrito con éxito | Total actualizadas: 232
Fila actualizada: 36185 | CSV sobrescrito con éxito | Total actualizadas: 233
Fila actualizada: 36187 | CSV sobrescrito con éxito | Total actualizadas: 234
Fila actualizada: 36190 | CSV sobrescrito con éxito | Total actualizadas: 235
Fila actualizada: 36194 | CSV sobrescrito con éxito | Total actualizadas: 236
Fila actualizada: 36195 | CSV sobrescrito con éxito | Total actualizadas: 237
Fila actualizada: 36200 | CSV sobrescrito con éxito | Total actualizadas: 238
Fila actualizada: 36210 | CSV sobrescrito con éxito | Total actualizadas: 239
Fila actualizada: 36218 | CSV sobrescrito con éxito | Total actualizadas: 240
Fila actualizada: 36220 | CSV sobrescrito con éxito | Total actualizadas: 241
Fila actualizada: 36229 | CSV sobrescrito con éxito | Total actualizadas: 242
Fila actualizada: 36230 | CSV sobrescrito con éxito | Total actualizadas: 243
Fila actualizada: 36237 | CSV sobrescrito con éxito | Total actualizadas: 244
Fila actualizada: 36238 | CSV sobrescrito con éxito | Total actualizadas: 245
Fila actualizada: 36247 | CSV sobrescrito con éxito | Total actualizadas: 246
Fila actualizada: 36248 | CSV sobrescrito con éxito | Total actualizadas: 247
Fila actualizada: 36250 | CSV sobrescrito con éxito | Total actualizadas: 248
Fila actualizada: 36252 | CSV sobrescrito con éxito | Total actualizadas: 249
Fila actualizada: 36265 | CSV sobrescrito con éxito | Total actualizadas: 250
Fila actualizada: 36269 | CSV sobrescrito con éxito | Total actualizadas: 251
Fila actualizada: 36275 | CSV sobrescrito con éxito | Total actualizadas: 252
Fila actualizada: 36276 | CSV sobrescrito con éxito | Total actualizadas: 253
Fila actualizada: 36279 | CSV sobrescrito con éxito | Total actualizadas: 254
Fila actualizada: 36282 | CSV sobrescrito con éxito | Total actualizadas: 255
Fila actualizada: 36284 | CSV sobrescrito con éxito | Total actualizadas: 256
Fila actualizada: 36285 | CSV sobrescrito con éxito | Total actualizadas: 257

,tipo,precio,localidad,latitud,longitud,superficie_construida,habitaciones,banyos,antiguedad,conservacion,...,orientacion,garaje,piscina,aire_acondicionado,trastero,ascensor,planta,fecha,detalle_url,Descripcion
0,Ático,70000,Alcoi Alcoy,38.700241,-0.481300,90.0,2.0,1.0,Entre 5 y 10 años,En buen estado,...,Desconocido,Desconocido,Sin piscina,False,True,False,5ª,2025-12-23,https://www.pisos.com/comprar/atico-alcoi_alco...,Desconocida_Revisada
1,Piso,139000,Ibi,38.624174,-0.574839,120.0,4.0,1.0,Entre 30 y 50 años,En buen estado,...,Este,Desconocido,Sin piscina,False,True,True,4ª,2026-02-24,https://www.pisos.com/comprar/piso-ibi_centro_...,En el municipio de ibi se encuentra este ampli...
2,Ático,950000,Alicante Alacant,38.380730,-0.410119,100.0,3.0,2.0,Desconocida,A reformar,...,Sur-Este,Privado,Comunitaria,False,False,True,10ª,2026-02-02,https://www.pisos.com/comprar/atico-playas_pla...,Desconocida_Revisada
3,Piso,200000,La Vila Joiosa Villajoyosa,38.502493,-0.241090,85.0,3.0,2.0,Entre 10 y 20 años,En buen estado,...,Desconocido,Desconocido,Sin piscina,True,True,True,0ª,2026-02-24,https://www.pisos.com/comprar/piso-montiboli_p...,"Piso en planta baja, superficie 85 m². Cuenta ..."
4,Piso,115000,Alcoi Alcoy,38.691936,-0.488745,90.0,4.0,2.0,Desconocida,En buen estado,...,Desconocido,Privado,Sin piscina,False,True,True,0ª,NaN,https://www.pisos.com/comprar/piso-alcoi_alcoy...,Desconocida_Revisada
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38009,Piso,95000,Elx Elche,38.269481,-0.686137,65.0,3.0,1.0,Más de 50 años,Reformado,...,Sur-Este,Desconocido,Sin piscina,True,False,False,1ª,2025-11-14,https://www.pisos.com/comprar/piso-elche_elx_c...,Desconocida_Revisada
38010,Piso,94000,Villena,38.635965,-0.867072,130.0,3.0,2.0,Entre 20 y 30 años,Reformado,...,Sur,Desconocido,Sin piscina,False,True,True,1ª,2026-02-13,https://www.pisos.com/comprar/piso-villena_cen...,Desconocida_Revisada
38011,Casa,150000,Callosa D'en Sarrià,38.650000,-0.123545,229.0,10.0,2.0,Más de 50 años,A reformar,...,Desconocido,Desconocido,Sin piscina,False,False,False,0ª,NaN,https://www.pisos.com/comprar/casa_rustica-cal...,Desconocida_Revisada
38012,Chalet,800000,La Nucia,38.611688,-0.127596,430.0,4.0,2.0,Entre 30 y 50 años,En buen estado,...,Desconocido,Privado,Sin piscina,False,False,False,0ª,2025-04-23,https://www.pisos.com/comprar/chalet_unifamili...,Venta chalet en parcela edificable en la nucia...
38013,Casa,99000,Benimarfull,38.775992,-0.390138,353.0,3.0,1.0,Más de 50 años,A reformar,...,Desconocido,Desconocido,Sin piscina,False,False,False,0ª,2023-10-20,https://www.pisos.com/comprar/casa_adosada-ben...,Casa ubicada en el pueblo de Benimarfull. Situ...

### Exportación del nuevo dataset

Una vez terminada la recolección, creamos un nuevo dataset llamado pisos_con_descripción_filtrado, donde nos quedamos solamente con las filas que tienen descripción, este número no coincide con el número total de filas debido a que muchos anuncios ya han seido borrados de la web:

In [ ]:
pisos_con_descripción_filtrado = pisos[pisos['Descripcion'] != 'Desconocida_Revisada']

pisos_con_descripción_filtrado.to_csv("pisos_con_descripción_filtrado.csv", sep=";", index=False)

## Enriquecimiento de los datos

Durante esta sección vamos a revisar mediante la descripción de cada anuncio con distintos modelos de LLM, las siguientes columnas:

* Antigüedad.
* Conservación.
* Terraza.
* Jardín.
* Garaje.
* Piscina.
* Aire acondicionado.
* Trastero.
* Ascensor.

### Qwen2.5-7B

#### Descarga del modelo

In [ ]:
# =========================
# 0. INSTALAR (solo si falta)
# =========================
import importlib

def install_if_missing(package):
    if importlib.util.find_spec(package) is None:
        !pip install -q {package}

install_if_missing("transformers")
install_if_missing("accelerate")
install_if_missing("bitsandbytes")
install_if_missing("huggingface_hub")

# =========================
# 1. MONTAR DRIVE
# =========================
from google.colab import drive
drive.mount('/content/drive')

# =========================
# 2. CONFIGURACIÓN
# =========================
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_id = "Qwen/Qwen2.5-7B-Instruct"

save_path = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/qwen_model"

# =========================
# 3. CUANTIZACIÓN
# =========================
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

# =========================
# 4. DESCARGAR MODELO
# =========================
tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    quantization_config=quantization_config
)

# =========================
# 5. GUARDAR EN DRIVE
# =========================
tokenizer.save_pretrained(save_path)
model.save_pretrained(save_path)

print("✅ Modelo guardado en:", save_path)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.8 MB/s eta 0:00:00
Mounted at /content/drive

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Modelo guardado en: /content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/qwen_model

#### Carga del modelo

In [4]:
# =========================
# 0. INSTALAR (solo si falta)
# =========================
import importlib

def install_if_missing(package):
    if importlib.util.find_spec(package) is None:
        !pip install -q {package}

install_if_missing("transformers")
install_if_missing("accelerate")
install_if_missing("bitsandbytes")

# =========================
# 1. MONTAR DRIVE
# =========================
from google.colab import drive
drive.mount('/content/drive')

# =========================
# 2. CONFIGURACIÓN
# =========================
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

load_path = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/qwen_model"

# =========================
# 3. CUANTIZACIÓN
# =========================
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

# =========================
# 4. CARGAR DESDE DRIVE
# =========================
tokenizer = AutoTokenizer.from_pretrained(load_path)

model = AutoModelForCausalLM.from_pretrained(
    load_path,
    device_map="auto",
    quantization_config=quantization_config
)

print("🚀 Modelo cargado desde Drive")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 14.6 MB/s eta 0:00:00
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.12/dist-packages/transformers/quantizers/auto.py:271: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

🚀 Modelo cargado desde Drive

#### Conservación

In [ ]:
pisos_origen = pisos.copy()
pisos_enriquecidos = pisos.copy()

Primero vamos a enriquecer la columna Conservación, preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_conservacion_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica el tipo de conservación que tiene. "
        "Responde estrictamente con una de estas 5 opciones:\n"
        "- 'A estrenar' (si la vivienda es nueva)\n"
        "- 'En buen estado' (si la vivienda no presenta defectos, no está reformada y tampoco es nueva)\n"
        "- 'Reformado' (si la vivienda ha sido reformada)\n"
        "- 'A reformar' (si la vivienda necesita ser reformada)\n"
        "- 'Desconocida Revisada' (si el tipo de conservación no es ninguno de los anteriores)"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "a estrenar" in resultado_clean:
        return "A estrenar"
    elif "reformado" in resultado_clean:
        return "Reformado"
    elif "a reformar" in resultado_clean:
        return "A reformar"
    elif "en buen estado" in resultado_clean:
        return "En buen estado"
    else:
        return "Desconocida Revisada"

Preparamos el código para recorrer todas las filas con conservación desconocida:

In [ ]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co = pisos_enriquecidos

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co[pisos_enriquecidos_Qwen_co["conservacion"] == "Desconocida"].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_conservacion_llm(descripcion)
        pisos_enriquecidos_Qwen_co.loc[idx, "conservacion"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co.to_csv(ruta, sep=";", index=False)

print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 0
✅ Proceso terminado

In [ ]:
pisos_origen['conservacion'].value_counts()

conservacion
Desconocida       10107
En buen estado     1268
A estrenar          427
A reformar          129
Reformado           101
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co['conservacion'].value_counts()

conservacion
A estrenar              6273
En buen estado          4311
Reformado                933
A reformar               299
Desconocida Revisada     216
Name: count, dtype: int64

#### Terraza

Cargamos el anterior dataset:

In [ ]:
pisos_enriquecidos_Qwen_co = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co.csv', sep=';')

print(pisos_enriquecidos_Qwen_co.duplicated().sum())

pisos_enriquecidos_Qwen_co['terraza'].value_counts()

0

terraza
False    6066
True     5966
Name: count, dtype: int64

Preparamos la nueva función con el nuevo prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_terraza_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica el tipo de terraza que tiene. "
        "Responde estrictamente con una de estas 2 opciones:\n"
        "- 'True' (si la vivienda tiene algún tipo de terraza)\n"
        "- 'False' (si la vivienda no tiene ningún tipo de terraza)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "true" in resultado_clean:
        return "True"
    elif "false" in resultado_clean:
        return "False Revisada"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con terraza:

In [ ]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te = pisos_enriquecidos_Qwen_co

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te[pisos_enriquecidos_Qwen_co_te["terraza"] == False].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_terraza_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te.loc[idx, "terraza"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 6066
Error en fila 8: Torch not compiled with CUDA enabled
Error en fila 13: Torch not compiled with CUDA enabled
Error en fila 14: Torch not compiled with CUDA enabled
Error en fila 15: Torch not compiled with CUDA enabled
Error en fila 19: Torch not compiled with CUDA enabled
Error en fila 37: Torch not compiled with CUDA enabled
Error en fila 40: Torch not compiled with CUDA enabled
Error en fila 42: Torch not compiled with CUDA enabled
Error en fila 44: Torch not compiled with CUDA enabled
Error en fila 45: Torch not compiled with CUDA enabled
Error en fila 46: Torch not compiled with CUDA enabled
Error en fila 48: Torch not compiled with CUDA enabled
Error en fila 49: Torch not compiled with CUDA enabled
Error en fila 50: Torch not compiled with CUDA enabled
Error en fila 110: Torch not compiled with CUDA enabled
Error en fila 122: Torch not compiled with CUDA enabled
Error en fila 176: Torch not compiled with CUDA enabled
Error en fila 178: Torch not compiled with CUDA enabled
Error en fila 186: Torch not compiled with CUDA enabled
Error en fila 190: Torch not compiled with CUDA enabled
Error en fila 191: Torch not compiled with CUDA enabled
Error en fila 192: Torch not compiled with CUDA enabled
Error en fila 193: Torch not compiled with CUDA enabled
Error en fila 197: Torch not compiled with CUDA enabled
Error en fila 198: Torch not compiled with CUDA enabled
Error en fila 202: Torch not compiled with CUDA enabled
Error en fila 204: Torch not compiled with CUDA enabled
Error en fila 206: Torch not compiled with CUDA enabled
Error en fila 207: Torch not compiled with CUDA enabled
Error en fila 210: Torch not compiled with CUDA enabled
Error en fila 216: Torch not compiled with CUDA enabled
Error en fila 217: Torch not compiled with CUDA enabled
Error en fila 218: Torch not compiled with CUDA enabled
Error en fila 222: Torch not compiled with CUDA enabled
Error en fila 225: Torch not compiled with CUDA enabled
Error en fila 230: Torch not compiled with CUDA enabled
Error en fila 231: Torch not compiled with CUDA enabled
Error en fila 232: Torch not compiled with CUDA enabled
Error en fila 233: Torch not compiled with CUDA enabled
Error en fila 235: Torch not compiled with CUDA enabled
Error en fila 236: Torch not compiled with CUDA enabled
Error en fila 238: Torch not compiled with CUDA enabled
Error en fila 240: Torch not compiled with CUDA enabled
Error en fila 244: Torch not compiled with CUDA enabled
Error en fila 249: Torch not compiled with CUDA enabled
Error en fila 250: Torch not compiled with CUDA enabled
Error en fila 252: Torch not compiled with CUDA enabled
Error en fila 253: Torch not compiled with CUDA enabled
Error en fila 257: Torch not compiled with CUDA enabled
Error en fila 259: Torch not compiled with CUDA enabled
Error en fila 262: Torch not compiled with CUDA enabled
Error en fila 264: Torch not compiled with CUDA enabled
Error en fila 266: Torch not compiled with CUDA enabled
Error en fila 267: Torch not compiled with CUDA enabled
Error en fila 268: Torch not compiled with CUDA enabled
Error en fila 277: Torch not compiled with CUDA enabled
Error en fila 279: Torch not compiled with CUDA enabled
Error en fila 283: Torch not compiled with CUDA enabled
Error en fila 284: Torch not compiled with CUDA enabled
Error en fila 287: Torch not compiled with CUDA enabled
Error en fila 288: Torch not compiled with CUDA enabled
Error en fila 289: Torch not compiled with CUDA enabled
Error en fila 290: Torch not compiled with CUDA enabled
Error en fila 293: Torch not compiled with CUDA enabled
Error en fila 296: Torch not compiled with CUDA enabled
Error en fila 302: Torch not compiled with CUDA enabled
Error en fila 306: Torch not compiled with CUDA enabled
Error en fila 308: Torch not compiled with CUDA enabled
Error en fila 310: Torch not compiled with CUDA enabled
Error en fila 311: Torch not compiled with CUDA enabled
Error en fila 316: Torch not compiled with CUDA enabled
Error en fila 317: Torch not compiled with CUDA enabled
Error en fila 318: Torch not compiled with CUDA enabled
Error en fila 331: Torch not compiled with CUDA enabled
Error en fila 332: Torch not compiled with CUDA enabled
Error en fila 338: Torch not compiled with CUDA enabled
Error en fila 356: Torch not compiled with CUDA enabled
Error en fila 366: Torch not compiled with CUDA enabled
Error en fila 367: Torch not compiled with CUDA enabled
Error en fila 370: Torch not compiled with CUDA enabled
Error en fila 372: Torch not compiled with CUDA enabled
Error en fila 374: Torch not compiled with CUDA enabled
Error en fila 378: Torch not compiled with CUDA enabled
Error en fila 379: Torch not compiled with CUDA enabled
Error en fila 382: Torch not compiled with CUDA enabled
Error en fila 383: Torch not compiled with CUDA enabled
Error en fila 394: Torch not compiled with CUDA enabled
Error en fila 397: Torch not compiled with CUDA enabled
Error en fila 402: Torch not compiled with CUDA enabled
Error en fila 403: Torch not compiled with CUDA enabled
Error en fila 404: Torch not compiled with CUDA enabled
Error en fila 406: Torch not compiled with CUDA enabled
Error en fila 410: Torch not compiled with CUDA enabled
Error en fila 416: Torch not compiled with CUDA enabled
Error en fila 418: Torch not compiled with CUDA enabled
Error en fila 419: Torch not compiled with CUDA enabled
Error en fila 421: Torch not compiled with CUDA enabled
Error en fila 422: Torch not compiled with CUDA enabled
Error en fila 425: Torch not compiled with CUDA enabled
Error en fila 427: Torch not compiled with CUDA enabled
Error en fila 431: Torch not compiled with CUDA enabled
Error en fila 432: Torch not compiled with CUDA enabled
Error en fila 433: Torch not compiled with CUDA enabled
Error en fila 434: Torch not compiled with CUDA enabled
Error en fila 441: Torch not compiled with CUDA enabled
Error en fila 444: Torch not compiled with CUDA enabled
Error en fila 447: Torch not compiled with CUDA enabled
Error en fila 451: Torch not compiled with CUDA enabled
Error en fila 453: Torch not compiled with CUDA enabled
Error en fila 456: Torch not compiled with CUDA enabled
Error en fila 459: Torch not compiled with CUDA enabled
Error en fila 461: Torch not compiled with CUDA enabled
Error en fila 462: Torch not compiled with CUDA enabled
Error en fila 463: Torch not compiled with CUDA enabled
Error en fila 467: Torch not compiled with CUDA enabled
Error en fila 468: Torch not compiled with CUDA enabled
Error en fila 469: Torch not compiled with CUDA enabled
Error en fila 471: Torch not compiled with CUDA enabled
Error en fila 479: Torch not compiled with CUDA enabled
Error en fila 480: Torch not compiled with CUDA enabled
Error en fila 481: Torch not compiled with CUDA enabled
Error en fila 484: Torch not compiled with CUDA enabled
Error en fila 486: Torch not compiled with CUDA enabled
Error en fila 490: Torch not compiled with CUDA enabled
Error en fila 492: Torch not compiled with CUDA enabled
Error en fila 494: Torch not compiled with CUDA enabled
Error en fila 495: Torch not compiled with CUDA enabled
Error en fila 500: Torch not compiled with CUDA enabled
Error en fila 501: Torch not compiled with CUDA enabled
Error en fila 502: Torch not compiled with CUDA enabled
Error en fila 506: Torch not compiled with CUDA enabled
Error en fila 508: Torch not compiled with CUDA enabled
Error en fila 512: Torch not compiled with CUDA enabled
Error en fila 513: Torch not compiled with CUDA enabled
Error en fila 516: Torch not compiled with CUDA enabled
Error en fila 517: Torch not compiled with CUDA enabled
Error en fila 522: Torch not compiled with CUDA enabled
Error en fila 530: Torch not compiled with CUDA enabled
Error en fila 534: Torch not compiled with CUDA enabled
Error en fila 535: Torch not compiled with CUDA enabled
Error en fila 536: Torch not compiled with CUDA enabled
Error en fila 537: Torch not compiled with CUDA enabled
Error en fila 538: Torch not compiled with CUDA enabled
Error en fila 539: Torch not compiled with CUDA enabled
Error en fila 542: Torch not compiled with CUDA enabled
Error en fila 543: Torch not compiled with CUDA enabled
Error en fila 544: Torch not compiled with CUDA enabled
Error en fila 545: Torch not compiled with CUDA enabled
Error en fila 546: Torch not compiled with CUDA enabled
Error en fila 549: Torch not compiled with CUDA enabled
Error en fila 554: Torch not compiled with CUDA enabled
Error en fila 561: Torch not compiled with CUDA enabled
Error en fila 562: Torch not compiled with CUDA enabled
Error en fila 563: Torch not compiled with CUDA enabled
Error en fila 565: Torch not compiled with CUDA enabled
Error en fila 566: Torch not compiled with CUDA enabled
Error en fila 569: Torch not compiled with CUDA enabled
Error en fila 570: Torch not compiled with CUDA enabled
Error en fila 571: Torch not compiled with CUDA enabled
Error en fila 574: Torch not compiled with CUDA enabled
Error en fila 576: Torch not compiled with CUDA enabled
Error en fila 577: Torch not compiled with CUDA enabled
Error en fila 580: Torch not compiled with CUDA enabled
Error en fila 582: Torch not compiled with CUDA enabled
Error en fila 583: Torch not compiled with CUDA enabled
Error en fila 585: Torch not compiled with CUDA enabled
Error en fila 586: Torch not compiled with CUDA enabled
Error en fila 588: Torch not compiled with CUDA enabled
Error en fila 591: Torch not compiled with CUDA enabled
Error en fila 600: Torch not compiled with CUDA enabled
Error en fila 607: Torch not compiled with CUDA enabled
Error en fila 629: Torch not compiled with CUDA enabled
Error en fila 638: Torch not compiled with CUDA enabled
Error en fila 641: Torch not compiled with CUDA enabled
Error en fila 646: Torch not compiled with CUDA enabled
Error en fila 648: Torch not compiled with CUDA enabled
Error en fila 654: Torch not compiled with CUDA enabled
Error en fila 656: Torch not compiled with CUDA enabled
Error en fila 657: Torch not compiled with CUDA enabled
Error en fila 658: Torch not compiled with CUDA enabled
Error en fila 659: Torch not compiled with CUDA enabled
Error en fila 660: Torch not compiled with CUDA enabled
Error en fila 662: Torch not compiled with CUDA enabled
Error en fila 664: Torch not compiled with CUDA enabled
Error en fila 668: Torch not compiled with CUDA enabled
Error en fila 669: Torch not compiled with CUDA enabled
Error en fila 675: Torch not compiled with CUDA enabled
Error en fila 677: Torch not compiled with CUDA enabled
Error en fila 680: Torch not compiled with CUDA enabled
Error en fila 681: Torch not compiled with CUDA enabled
Error en fila 682: Torch not compiled with CUDA enabled
Error en fila 684: Torch not compiled with CUDA enabled
Error en fila 685: Torch not compiled with CUDA enabled
Error en fila 686: Torch not compiled with CUDA enabled
Error en fila 688: Torch not compiled with CUDA enabled
Error en fila 689: Torch not compiled with CUDA enabled
Error en fila 694: Torch not compiled with CUDA enabled
Error en fila 697: Torch not compiled with CUDA enabled
Error en fila 704: Torch not compiled with CUDA enabled
Error en fila 706: Torch not compiled with CUDA enabled
Error en fila 708: Torch not compiled with CUDA enabled
Error en fila 709: Torch not compiled with CUDA enabled
Error en fila 710: Torch not compiled with CUDA enabled
Error en fila 712: Torch not compiled with CUDA enabled
Error en fila 714: Torch not compiled with CUDA enabled
Error en fila 716: Torch not compiled with CUDA enabled
Error en fila 717: Torch not compiled with CUDA enabled
Error en fila 719: Torch not compiled with CUDA enabled
Error en fila 720: Torch not compiled with CUDA enabled
Error en fila 721: Torch not compiled with CUDA enabled
Error en fila 722: Torch not compiled with CUDA enabled
Error en fila 724: Torch not compiled with CUDA enabled
Error en fila 726: Torch not compiled with CUDA enabled
Error en fila 727: Torch not compiled with CUDA enabled
Error en fila 728: Torch not compiled with CUDA enabled
Error en fila 729: Torch not compiled with CUDA enabled
Error en fila 730: Torch not compiled with CUDA enabled
Error en fila 731: Torch not compiled with CUDA enabled
Error en fila 733: Torch not compiled with CUDA enabled
Error en fila 737: Torch not compiled with CUDA enabled
Error en fila 745: Torch not compiled with CUDA enabled
Error en fila 747: Torch not compiled with CUDA enabled
Error en fila 749: Torch not compiled with CUDA enabled
Error en fila 750: Torch not compiled with CUDA enabled
Error en fila 751: Torch not compiled with CUDA enabled
Error en fila 755: Torch not compiled with CUDA enabled
Error en fila 757: Torch not compiled with CUDA enabled
Error en fila 759: Torch not compiled with CUDA enabled
Error en fila 770: Torch not compiled with CUDA enabled
Error en fila 772: Torch not compiled with CUDA enabled
Error en fila 776: Torch not compiled with CUDA enabled
Error en fila 783: Torch not compiled with CUDA enabled
Error en fila 785: Torch not compiled with CUDA enabled
Error en fila 787: Torch not compiled with CUDA enabled
Error en fila 791: Torch not compiled with CUDA enabled
Error en fila 792: Torch not compiled with CUDA enabled
Error en fila 793: Torch not compiled with CUDA enabled
Error en fila 796: Torch not compiled with CUDA enabled
Error en fila 797: Torch not compiled with CUDA enabled
Error en fila 798: Torch not compiled with CUDA enabled
Error en fila 806: Torch not compiled with CUDA enabled
Error en fila 808: Torch not compiled with CUDA enabled
Error en fila 818: Torch not compiled with CUDA enabled
Error en fila 823: Torch not compiled with CUDA enabled
Error en fila 824: Torch not compiled with CUDA enabled
Error en fila 825: Torch not compiled with CUDA enabled
Error en fila 828: Torch not compiled with CUDA enabled
Error en fila 831: Torch not compiled with CUDA enabled
Error en fila 834: Torch not compiled with CUDA enabled
Error en fila 836: Torch not compiled with CUDA enabled
Error en fila 860: Torch not compiled with CUDA enabled
Error en fila 862: Torch not compiled with CUDA enabled
Error en fila 869: Torch not compiled with CUDA enabled
Error en fila 871: Torch not compiled with CUDA enabled
Error en fila 880: Torch not compiled with CUDA enabled
Error en fila 885: Torch not compiled with CUDA enabled
Error en fila 886: Torch not compiled with CUDA enabled
Error en fila 887: Torch not compiled with CUDA enabled
Error en fila 896: Torch not compiled with CUDA enabled
Error en fila 898: Torch not compiled with CUDA enabled
Error en fila 899: Torch not compiled with CUDA enabled
Error en fila 906: Torch not compiled with CUDA enabled
Error en fila 912: Torch not compiled with CUDA enabled
Error en fila 921: Torch not compiled with CUDA enabled
Error en fila 922: Torch not compiled with CUDA enabled
Error en fila 925: Torch not compiled with CUDA enabled
Error en fila 937: Torch not compiled with CUDA enabled
Error en fila 939: Torch not compiled with CUDA enabled
Error en fila 944: Torch not compiled with CUDA enabled
Error en fila 948: Torch not compiled with CUDA enabled
Error en fila 951: Torch not compiled with CUDA enabled
Error en fila 956: Torch not compiled with CUDA enabled
Error en fila 962: Torch not compiled with CUDA enabled
Error en fila 966: Torch not compiled with CUDA enabled
Error en fila 983: Torch not compiled with CUDA enabled
Error en fila 985: Torch not compiled with CUDA enabled
Error en fila 991: Torch not compiled with CUDA enabled
Error en fila 994: Torch not compiled with CUDA enabled
Error en fila 996: Torch not compiled with CUDA enabled
Error en fila 1004: Torch not compiled with CUDA enabled
Error en fila 1007: Torch not compiled with CUDA enabled
Error en fila 1010: Torch not compiled with CUDA enabled
Error en fila 1029: Torch not compiled with CUDA enabled
Error en fila 1031: Torch not compiled with CUDA enabled
Error en fila 1041: Torch not compiled with CUDA enabled
Error en fila 1043: Torch not compiled with CUDA enabled
Error en fila 1046: Torch not compiled with CUDA enabled
Error en fila 1051: Torch not compiled with CUDA enabled
Error en fila 1056: Torch not compiled with CUDA enabled
Error en fila 1057: Torch not compiled with CUDA enabled
Error en fila 1058: Torch not compiled with CUDA enabled
Error en fila 1061: Torch not compiled with CUDA enabled
Error en fila 1064: Torch not compiled with CUDA enabled
Error en fila 1066: Torch not compiled with CUDA enabled
Error en fila 1067: Torch not compiled with CUDA enabled
Error en fila 1069: Torch not compiled with CUDA enabled
Error en fila 1079: Torch not compiled with CUDA enabled
Error en fila 1080: Torch not compiled with CUDA enabled
Error en fila 1082: Torch not compiled with CUDA enabled
Error en fila 1088: Torch not compiled with CUDA enabled
Error en fila 1089: Torch not compiled with CUDA enabled
Error en fila 1094: Torch not compiled with CUDA enabled
Error en fila 1096: Torch not compiled with CUDA enabled
Error en fila 1107: Torch not compiled with CUDA enabled
Error en fila 1108: Torch not compiled with CUDA enabled
Error en fila 1109: Torch not compiled with CUDA enabled
Error en fila 1111: Torch not compiled with CUDA enabled
Error en fila 1119: Torch not compiled with CUDA enabled
Error en fila 1123: Torch not compiled with CUDA enabled
Error en fila 1131: Torch not compiled with CUDA enabled
Error en fila 1133: Torch not compiled with CUDA enabled
Error en fila 1148: Torch not compiled with CUDA enabled
Error en fila 1150: Torch not compiled with CUDA enabled
Error en fila 1157: Torch not compiled with CUDA enabled
Error en fila 1160: Torch not compiled with CUDA enabled
Error en fila 1162: Torch not compiled with CUDA enabled
Error en fila 1164: Torch not compiled with CUDA enabled
Error en fila 1165: Torch not compiled with CUDA enabled
Error en fila 1175: Torch not compiled with CUDA enabled
Error en fila 1182: Torch not compiled with CUDA enabled
Error en fila 1197: Torch not compiled with CUDA enabled
Error en fila 1203: Torch not compiled with CUDA enabled
Error en fila 1205: Torch not compiled with CUDA enabled
Error en fila 1208: Torch not compiled with CUDA enabled
Error en fila 1217: Torch not compiled with CUDA enabled
Error en fila 1232: Torch not compiled with CUDA enabled
Error en fila 1234: Torch not compiled with CUDA enabled
Error en fila 1241: Torch not compiled with CUDA enabled
Error en fila 1244: Torch not compiled with CUDA enabled
Error en fila 1250: Torch not compiled with CUDA enabled
Error en fila 1253: Torch not compiled with CUDA enabled
Error en fila 1258: Torch not compiled with CUDA enabled
Error en fila 1262: Torch not compiled with CUDA enabled
Error en fila 1264: Torch not compiled with CUDA enabled
Error en fila 1272: Torch not compiled with CUDA enabled
Error en fila 1277: Torch not compiled with CUDA enabled
Error en fila 1285: Torch not compiled with CUDA enabled
Error en fila 1288: Torch not compiled with CUDA enabled
Error en fila 1290: Torch not compiled with CUDA enabled
Error en fila 1300: Torch not compiled with CUDA enabled
Error en fila 1304: Torch not compiled with CUDA enabled
Error en fila 1311: Torch not compiled with CUDA enabled
Error en fila 1312: Torch not compiled with CUDA enabled
Error en fila 1313: Torch not compiled with CUDA enabled
Error en fila 1315: Torch not compiled with CUDA enabled
Error en fila 1336: Torch not compiled with CUDA enabled
Error en fila 1341: Torch not compiled with CUDA enabled
Error en fila 1355: Torch not compiled with CUDA enabled
Error en fila 1359: Torch not compiled with CUDA enabled
Error en fila 1366: Torch not compiled with CUDA enabled
Error en fila 1369: Torch not compiled with CUDA enabled
Error en fila 1393: Torch not compiled with CUDA enabled
Error en fila 1401: Torch not compiled with CUDA enabled
Error en fila 1406: Torch not compiled with CUDA enabled
Error en fila 1408: Torch not compiled with CUDA enabled

KeyboardInterrupt:

In [ ]:
pisos_enriquecidos_Qwen_co['terraza'].value_counts()

terraza
False    6066
True     5966
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te.csv', sep=';')

pisos_enriquecidos_Qwen_co_te['terraza'].value_counts()

terraza
True              6070
False Revisada    5962
Name: count, dtype: int64

#### Jardín

Cargamos el dataset:

In [ ]:
pisos_enriquecidos_Qwen_co_te = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_jardin_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica el tipo de jardin que tiene. "
        "Responde estrictamente con una de estas 3 opciones:\n"
        "- 'Privado' (si la vivienda tiene jardín privado)\n"
        "- 'Comunitario' (si la vivienda tiene jardín comunitario)\n"
        "- 'Sin Jardín' (si la vivienda no tiene jardín)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "privado" in resultado_clean:
        return "Privado"
    elif "comunitario" in resultado_clean:
        return "Comunitario"
    elif "sin jardin" in resultado_clean:
        return "Sin Jardín"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con terraza:

In [ ]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja = pisos_enriquecidos_Qwen_co_te

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja[pisos_enriquecidos_Qwen_co_te_ja["jardin"] == "Desconocido"].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_jardin_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja.loc[idx, "jardin"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 66
Procesadas 0/66
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te['jardin'].value_counts()

jardin
False          5909
Privado        3145
Desconocido    2769
Comunitario     209
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja['jardin'].value_counts()

jardin
False                   5909
Privado                 3987
Desconocida Revisada    1608
Comunitario              528
Name: count, dtype: int64

#### Garaje

Cargamos el dataset anterior:

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_garaje_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica el tipo de garaje que tiene. "
        "Responde estrictamente con una de estas 4 opciones:\n"
        "- 'Privado' (si la vivienda tiene garaje privado)\n"
        "- 'Comunitario' (si la vivienda tiene garaje comunitario)\n"
        "- 'Opcional' (si en la vivienda existe la opción de garaje)\n"
        "- 'Sin garaje' (si la vivienda no tiene garaje)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "privado" in resultado_clean:
        return "Privado"
    elif "comunitario" in resultado_clean:
        return "Comunitario"
    elif "opcional" in resultado_clean:
        return "Opcional"
    elif "sin garaje" in resultado_clean:
        return "Sin Garaje"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con garaje:

In [ ]:
import pandas as pd
import torch

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga = pisos_enriquecidos_Qwen_co_te_ja

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga[pisos_enriquecidos_Qwen_co_te_ja_ga["garaje"] == "Desconocido"].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_garaje_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga.loc[idx, "garaje"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo aún no existe
Filas a procesar: 3906
Procesadas 0/3906
Procesadas 100/3906
Procesadas 200/3906
Procesadas 300/3906
Procesadas 400/3906
Procesadas 500/3906
Procesadas 600/3906
Procesadas 700/3906
Procesadas 800/3906
Procesadas 900/3906
Procesadas 1000/3906
Procesadas 1100/3906
Procesadas 1200/3906
Procesadas 1300/3906
Procesadas 1400/3906
Procesadas 1500/3906
Procesadas 1600/3906
Procesadas 1700/3906
Procesadas 1800/3906
Procesadas 1900/3906
Procesadas 2000/3906
Procesadas 2100/3906
Procesadas 2200/3906
Procesadas 2300/3906
Procesadas 2400/3906
Procesadas 2500/3906
Procesadas 2600/3906
Procesadas 2700/3906
Procesadas 2800/3906
Procesadas 2900/3906
Procesadas 3000/3906
Procesadas 3100/3906
Procesadas 3200/3906
Procesadas 3300/3906
Procesadas 3400/3906
Procesadas 3500/3906
Procesadas 3600/3906
Procesadas 3700/3906
Procesadas 3800/3906
Procesadas 3900/3906
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja['garaje'].value_counts()

garaje
False          5909
Desconocido    3906
Privado        2216
Opcional          1
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga['garaje'].value_counts()

garaje
False                   5909
Privado                 3373
Sin Garaje              2416
Opcional                 241
Desconocida Revisada      53
Comunitario               40
Name: count, dtype: int64

#### Piscina

Cargamos el dataset anterior:

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_piscina_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica el tipo de piscina que tiene. "
        "Responde estrictamente con una de estas 4 opciones:\n"
        "- 'Privada' (si la vivienda tiene piscina privada)\n"
        "- 'Comunitaria' (si la vivienda tiene piscina comunitaria)\n"
        "- 'Climatizada' (si la vivienda tiene piscina climatizada)\n"
        "- 'Sin piscina' (si la vivienda no tiene piscina)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "privada" in resultado_clean:
        return "Privada"
    elif "comunitaria" in resultado_clean:
        return "Comunitaria"
    elif "climatizada" in resultado_clean:
        return "Climatizada"
    elif "sin piscina" in resultado_clean:
        return "Sin Piscina"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con piscina:

In [ ]:
import pandas as pd
import torch

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi = pisos_enriquecidos_Qwen_co_te_ja_ga

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga_pi[pisos_enriquecidos_Qwen_co_te_ja_ga_pi["piscina"] == "Sin piscina"].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga_pi.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_piscina_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga_pi.loc[idx, "piscina"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga_pi.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga_pi.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 276
Procesadas 0/276
Procesadas 100/276
Procesadas 200/276
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga['piscina'].value_counts()

piscina
False          5909
Exterior       2848
Sin piscina    1777
Comunitaria    1475
Climatizada      23
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi['piscina'].value_counts()

piscina
False          5909
Exterior       2848
Comunitaria    1604
Sin Piscina    1446
Privada         191
Climatizada      34
Name: count, dtype: int64

In [ ]:
import pandas as pd
import torch

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi = pisos_enriquecidos_Qwen_co_te_ja_ga.copy()

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga_pi[pisos_enriquecidos_Qwen_co_te_ja_ga_pi["piscina"] == "False"].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga_pi.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_piscina_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga_pi.loc[idx, "piscina"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga_pi.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga_pi.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 5908
Procesadas 0/5908
Procesadas 100/5908
Procesadas 200/5908
Procesadas 300/5908
Procesadas 400/5908
Procesadas 500/5908
Procesadas 600/5908
Procesadas 700/5908
Procesadas 800/5908
Procesadas 900/5908
Procesadas 1000/5908
Procesadas 1100/5908
Procesadas 1200/5908
Procesadas 1300/5908
Procesadas 1400/5908
Procesadas 1500/5908
Procesadas 1600/5908
Procesadas 1700/5908
Procesadas 1800/5908
Procesadas 1900/5908
Procesadas 2000/5908
Procesadas 2100/5908
Procesadas 2200/5908
Procesadas 2300/5908
Procesadas 2400/5908
Procesadas 2500/5908
Procesadas 2600/5908
Procesadas 2700/5908
Procesadas 2800/5908
Procesadas 2900/5908
Procesadas 3000/5908
Procesadas 3100/5908
Procesadas 3200/5908
Procesadas 3300/5908
Procesadas 3400/5908
Procesadas 3500/5908
Procesadas 3600/5908
Procesadas 3700/5908
Procesadas 3800/5908
Procesadas 3900/5908
Procesadas 4000/5908
Procesadas 4100/5908
Procesadas 4200/5908
Procesadas 4300/5908
Procesadas 4400/5908
Procesadas 4500/5908
Procesadas 4600/5908
Procesadas 4700/5908
Procesadas 4800/5908
Procesadas 4900/5908
Procesadas 5000/5908
Procesadas 5100/5908
Procesadas 5200/5908
Procesadas 5300/5908
Procesadas 5400/5908
Procesadas 5500/5908
Procesadas 5600/5908
Procesadas 5700/5908
Procesadas 5800/5908
Procesadas 5900/5908
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi['piscina'].value_counts()

piscina
Sin Piscina    7355
Exterior       2848
Comunitaria    1604
Privada         191
Climatizada      34
Name: count, dtype: int64

#### Aire acondicionado

Cargamos el dataset anterior:

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_aire_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica si tiene aire acondicionado. "
        "Responde estrictamente con una de estas 2 opciones:\n"
        "- 'True' (si la vivienda tiene aire acondicionado)\n"
        "- 'False' (si la vivienda no tiene aire acondicionado)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "true" in resultado_clean:
        return "True"
    elif "false" in resultado_clean:
        return "False Revisada"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con aire acondicionado:

In [ ]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai = pisos_enriquecidos_Qwen_co_te_ja_ga_pi.copy()

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai[pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai["aire_acondicionado"] == 'False'].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_aire_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.loc[idx, "aire_acondicionado"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 1861
Procesadas 0/1861
Procesadas 100/1861
Procesadas 200/1861
Procesadas 300/1861
Procesadas 400/1861
Procesadas 500/1861
Procesadas 600/1861
Procesadas 700/1861
Procesadas 800/1861
Procesadas 900/1861
Procesadas 1000/1861
Procesadas 1100/1861
Procesadas 1200/1861
Procesadas 1300/1861
Procesadas 1400/1861
Procesadas 1500/1861
Procesadas 1600/1861
Procesadas 1700/1861
Procesadas 1800/1861
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi['aire_acondicionado'].value_counts()

aire_acondicionado
False    8764
True     3268
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai['aire_acondicionado'].value_counts()

aire_acondicionado
False Revisada    8098
True              3934
Name: count, dtype: int64

#### Trastero

Cargamos el dataset anterior:

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_trastero_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica si tiene trastero. "
        "Responde estrictamente con una de estas 2 opciones:\n"
        "- 'True' (si la vivienda tiene trastero)\n"
        "- 'False' (si la vivienda no tiene trastero)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "true" in resultado_clean:
        return "True"
    elif "false" in resultado_clean:
        return "False Revisada"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con piscina:

In [ ]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai.copy()

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr[pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr["trastero"] == 'False'].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_trastero_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.loc[idx, "trastero"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 5541
Procesadas 0/5541
Procesadas 100/5541
Procesadas 200/5541
Procesadas 300/5541
Procesadas 400/5541
Procesadas 500/5541
Procesadas 600/5541
Procesadas 700/5541
Procesadas 800/5541
Procesadas 900/5541
Procesadas 1000/5541
Procesadas 1100/5541
Procesadas 1200/5541
Procesadas 1300/5541
Procesadas 1400/5541
Procesadas 1500/5541
Procesadas 1600/5541
Procesadas 1700/5541
Procesadas 1800/5541
Procesadas 1900/5541
Procesadas 2000/5541
Procesadas 2100/5541
Procesadas 2200/5541
Procesadas 2300/5541
Procesadas 2400/5541
Procesadas 2500/5541
Procesadas 2600/5541
Procesadas 2700/5541
Procesadas 2800/5541
Procesadas 2900/5541
Procesadas 3000/5541
Procesadas 3100/5541
Procesadas 3200/5541
Procesadas 3300/5541
Procesadas 3400/5541
Procesadas 3500/5541
Procesadas 3600/5541
Procesadas 3700/5541
Procesadas 3800/5541
Procesadas 3900/5541
Procesadas 4000/5541
Procesadas 4100/5541
Procesadas 4200/5541
Procesadas 4300/5541
Procesadas 4400/5541
Procesadas 4500/5541
Procesadas 4600/5541
Procesadas 4700/5541
Procesadas 4800/5541
Procesadas 4900/5541
Procesadas 5000/5541
Procesadas 5100/5541
Procesadas 5200/5541
Procesadas 5300/5541
Procesadas 5400/5541
Procesadas 5500/5541
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai['trastero'].value_counts()

trastero
False    9942
True     2090
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr['trastero'].value_counts()

trastero
False Revisada    8050
True              3982
Name: count, dtype: int64

#### Ascensor

Cargamos el dataset anterior:

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.csv', sep=';')

Preparamos el prompt:

In [ ]:
# 1. Definimos la función que habla con el modelo
def clasifica_ascensor_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica si tiene ascensor. "
        "Responde estrictamente con una de estas 2 opciones:\n"
        "- 'True' (si la vivienda tiene ascensor)\n"
        "- 'False' (si la vivienda no tiene ascensor)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "true" in resultado_clean:
        return "True"
    elif "false" in resultado_clean:
        return "False Revisada"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con piscina:

In [ ]:
import pandas as pd
import torch

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr.copy()

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as[pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as["ascensor"] == 'False'].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_ascensor_llm(descripcion)
        pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as.loc[idx, "ascensor"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo aún no existe
Filas a procesar: 0
✅ Proceso terminado

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr['ascensor'].value_counts()

ascensor
False    9331
True     2701
Name: count, dtype: int64

In [ ]:
pisos_enriquecidos_Qwen_co_te_ja_ga_pi_ai_tr_as['ascensor'].value_counts()

ascensor
False    9331
True     2701
Name: count, dtype: int64

#### Aire acondicionado (Repetir)

Cargamos el dataset anterior:

In [5]:
pisos_qwen = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_definitivo.csv', sep=';')

print(pisos_qwen.duplicated().sum())

pisos_qwen['aire_acondicionado'].value_counts()

0

aire_acondicionado
False    7685
True     4347
Name: count, dtype: int64

Preparamos el prompt:

In [6]:
# 1. Definimos la función que habla con el modelo
def clasifica_aire_llm(descripcion):

    prompt = (
        "Analiza la siguiente descripción de una vivienda y clasifica si tiene aire acondicionado. "
        "Responde estrictamente con una de estas 2 opciones:\n"
        "- 'True' (si la vivienda tiene aire acondicionado)\n"
        "- 'False' (si la vivienda no tiene aire acondicionado)\n"
        f"Descripción: {descripcion}"
    )
    messages = [{"role": "user", "content": prompt}]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

    model_inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad(): # Esto ahorra memoria GPU al procesar
        generated_ids = model.generate(**model_inputs, max_new_tokens=10, pad_token_id=tokenizer.eos_token_id)

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    resultado = response.split("assistant\n")[-1].strip().upper()
    # print(resultado)
    # Limpieza rápida por si el modelo añade un punto final o mayúsculas/minúsculas
    resultado_clean = resultado.lower()
    if "true" in resultado_clean:
        return "True"
    elif "false" in resultado_clean:
        return "False Revisada"
    else:
        return "Desconocida Revisada"

Preparamos el codigo para recorrer todas las filas con aire acondicionado:

In [7]:
import pandas as pd
import torch
import os

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

ruta = "/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_definitivo2.csv"

if os.path.exists(ruta):
    print("El archivo ya existe")
    pisos_qwen2 = pd.read_csv(ruta, sep=";")
else:
    print("El archivo aún no existe")
    pisos_qwen2 = pisos_qwen.copy()

# =========================
# 3. PROCESAMIENTO
# =========================
indices = pisos_qwen2[pisos_qwen2["aire_acondicionado"] == 'False'].index

print(f"Filas a procesar: {len(indices)}")
guardar_cada = 100

for i, idx in enumerate(indices):
    descripcion = pisos_qwen2.loc[idx, "Descripcion"]

    try:
        nueva_clasificacion = clasifica_aire_llm(descripcion)
        pisos_qwen2.loc[idx, "aire_acondicionado"] = nueva_clasificacion

    except Exception as e:
        print(f"Error en fila {idx}: {e}")
        continue

    # =========================
    # 4. GUARDADO ITERATIVO
    # =========================
    if i % guardar_cada == 0:
      pisos_qwen2.to_csv(ruta, sep=";", index=False)

    if i % guardar_cada == 0:
        print(f"Procesadas {i}/{len(indices)}")

pisos_qwen2.to_csv(ruta, sep=";", index=False)
print("✅ Proceso terminado")

El archivo ya existe
Filas a procesar: 4084
Procesadas 0/4084
Procesadas 100/4084
Procesadas 200/4084
Procesadas 300/4084
Procesadas 400/4084
Procesadas 500/4084
Procesadas 600/4084
Procesadas 700/4084
Procesadas 800/4084
Procesadas 900/4084
Procesadas 1000/4084
Procesadas 1100/4084
Procesadas 1200/4084
Procesadas 1300/4084
Procesadas 1400/4084
Procesadas 1500/4084
Procesadas 1600/4084
Procesadas 1700/4084
Procesadas 1800/4084
Procesadas 1900/4084
Procesadas 2000/4084
Procesadas 2100/4084
Procesadas 2200/4084
Procesadas 2300/4084
Procesadas 2400/4084
Procesadas 2500/4084
Procesadas 2600/4084
Procesadas 2700/4084
Procesadas 2800/4084
Procesadas 2900/4084
Procesadas 3000/4084
Procesadas 3100/4084
Procesadas 3200/4084
Procesadas 3300/4084
Procesadas 3400/4084
Procesadas 3500/4084
Procesadas 3600/4084
Procesadas 3700/4084
Procesadas 3800/4084
Procesadas 3900/4084
Procesadas 4000/4084
✅ Proceso terminado

In [8]:
pisos_qwen['aire_acondicionado'].value_counts()

aire_acondicionado
False    7685
True     4347
Name: count, dtype: int64

In [9]:
pisos_qwen2['aire_acondicionado'].value_counts()

aire_acondicionado
True              6787
False Revisada    5245
Name: count, dtype: int64

## EDA

In [3]:
pisos_qwen = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/TFM/AñadimosDescripciones/DatasetsEnriquecidos/Qwen/pisos_enriquecidos_Qwen_definitivo.csv', sep=';')

columnas = [
    "conservacion",
    "terraza",
    "jardin",
    "garaje",
    "piscina",
    "aire_acondicionado",
    "trastero",
    "ascensor",
]

for col in columnas:
    print(f"=== {col.upper()} ===")
    print(pisos_qwen[col].value_counts(dropna=False))
    print("\n")

=== CONSERVACION ===
conservacion
A estrenar              6273
En buen estado          4311
Reformado                933
A reformar               299
Desconocida Revisada     216
Name: count, dtype: int64


=== TERRAZA ===
terraza
True              10129
False Revisada     1903
Name: count, dtype: int64


=== JARDIN ===
jardin
Privado                 7006
Sin Jardín              3766
Comunitario             1254
Desconocida Revisada       6
Name: count, dtype: int64


=== GARAJE ===
garaje
Privado                 5557
Sin Garaje              5478
Opcional                 653
Comunitario              184
Desconocida Revisada     160
Name: count, dtype: int64


=== PISCINA ===
piscina
Exterior                5727
Sin Piscina             3036
Comunitaria             2361
Desconocida Revisada     844
Climatizada               63
Privada                    1
Name: count, dtype: int64


=== AIRE_ACONDICIONADO ===
aire_acondicionado
True              6787
False Revisada    5245
Name: count, dtype: int64


=== TRASTERO ===
trastero
False Revisada    8050
True              3982
Name: count, dtype: int64


=== ASCENSOR ===
ascensor
False Revisada    8709
True              3323
Name: count, dtype: int64

In [4]:
print(pisos_qwen.duplicated().sum())

0